server {
    listen 80;
    server_name acv-company.com www.acv-company.com localhost;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name acv-company.com www.acv-company.com;
    charset utf-8;

    ssl_certificate /etc/letsencrypt/live/acv-company.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/acv-company.com/privkey.pem;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy API sang Backend (port 8080)
    location /api/ {
        proxy_pass http://180.93.42.16:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /auth/ {
        proxy_pass http://180.93.42.16:8080/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
