services:
  - type: web
    name: fe-acv
    runtime: static
    buildCommand: npm run build
    staticPublishPath: dist/fe_acv/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
